{% set name = "openscenegraph" %}
{% set version = "3.6.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/openscenegraph/OpenSceneGraph/archive/OpenSceneGraph-{{ version }}.tar.gz
  sha256: aea196550f02974d6d09291c5d83b51ca6a03b3767e234a8c0e21322927d1e12
  patches:
    - osg.patch
    - cmake.patch  # [win]
    - collada-dom.patch

build:
  number: 11
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - pkg-config
    - doxygen
    - graphviz       # [unix]
    - graphviz 2.38  # [win]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('libselinux-devel') }}      # [linux]
    - {{ cdt('libxdamage-devel') }}      # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxfixes-devel') }}       # [linux]
    - {{ cdt('libxau-devel') }}          # [linux]
    - {{ cdt('libxfixes') }}             # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]
    - {{ cdt('libxext') }}               # [linux]
    - {{ cdt('libxcb') }}                # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
  host:
    - expat
    - freetype
    - libjpeg-turbo
    - jpeg
    - freetype
    - zlib
    - libtiff
    - libcurl
    - libpng
    - ffmpeg
    - fontconfig
    - collada-dom
  run:
    - expat
    - freetype
    - libjpeg-turbo
    - jpeg
    - freetype
    - zlib
    - libtiff
    - libcurl
    - libpng
    - ffmpeg
    - fontconfig
    - collada-dom

test:
  requires:
    - pkg-config
  commands:
    - pkg-config --modversion {{ name }}  # [unix]
    - test -f $PREFIX/include/osg/ref_ptr  # [unix]
    - if not exist %PREFIX%\\Library\\include\\osg\\ref_ptr exit 1  # [win]

about:
  home: http://github.com/openscenegraph/OpenSceneGraph
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: LICENSE.txt
  summary: 'OpenSceneGraph, an open source high performance 3D graphics toolkit'

  description: |
    The OpenSceneGraph is an open source high performance 3D graphics toolkit, used by application developers in fields such as visual simulation, games, virtual reality, scientific visualization and modelling. Written entirely in Standard C++ and OpenGL it runs on all Windows platforms, OSX, GNU/Linux, IRIX, Solaris, HP-Ux, AIX and FreeBSD operating systems. The OpenSceneGraph is now well established as the world leading scene graph technology, used widely in the vis-sim, space, scientific, oil-gas, games and virtual reality industries.
  doc_url: http://www.openscenegraph.org/index.php/documentation
  dev_url: http://github.com/openscenegraph/OpenSceneGraph

extra:
  recipe-maintainers:
    - jcarpent
